AWSTemplateFormatVersion: '2010-09-09'
Description: ecs task definition

Resources:
# ------------------------------------------------------------#
#  Role
# ------------------------------------------------------------#
  ecsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ecs-tasks.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite

# ------------------------------------------------------------#
#  TaskDefinition
# ------------------------------------------------------------#
  Taskdefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: ecsTaskExecutionRole
    Properties:
      Family: cfn-secrets-sample
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ecsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ecsTaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: cfn-secrets-sample-container
          Image: hamako9999/list-environments-php-container:latest
          PortMappings:
            - ContainerPort: 80
          Secrets:
            - Name: HAMADA_SECRETS
              ValueFrom: hamako-favorite-word
